
ALTER TABLE "AUTHHELPER_DIAGNOSTIC_WEB_ELEMENT" ADD COLUMN "SELECTORTYPE" INTEGER NULL BEFORE "FORMINDEX";

ALTER TABLE "AUTHHELPER_DIAGNOSTIC_WEB_ELEMENT" ADD COLUMN "SELECTORVALUE" VARCHAR(4096) NULL BEFORE "FORMINDEX";

