  - type: openapi                      # OpenAPI definition import
    parameters:
      apiFile:                         # String: Local file containing the OpenAPI definition, default: null, no definition will be imported
      apiUrl:                          # String: URL containing the OpenAPI definition, default: null, no definition will be imported
      context:                         # String: Context to use when importing the OpenAPI definition, default: first context.
      user:                            # String: An optional user to use for authentication, must be defined in the env.
      targetUrl:                       # String: URL which overrides the target defined in the definition, default: null, the target will not be overridden
