name: CI Remote

on:
  workflow_dispatch:
  schedule:
    # Once a month
    - cron:  '0 8 18 * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: 17
      - uses: gradle/actions/setup-gradle@50e97c2cd7a37755bbfafc9c5b7cafaece252f6e # v6.1.0
        with:
          gradle-home-cache-includes: |
            caches
            notifications
      - run: ./gradlew -Dorg.gradle.jvmargs=-Xmx4g --continue --no-parallel test
        env:
          ZAP_REMOTE_TESTS: 1
      - name: Publish JUnit report
        if: always()
        uses: step-security/action-junit-report@6c33c83bbe7511864f70174ba8275e4ea1174e21 # v6.4.0
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'
          detailed_summary: true
