name: Create Wappalyzer Update PR

on:
  schedule:
    - cron:  '0 4 3 * *'
  workflow_dispatch:

jobs:
  create_pr:
    name: Create Pull Request
    if: github.actor == 'kingthorin' || github.actor == 'psiinon' || github.actor == 'thc202'
    runs-on: ubuntu-latest
    steps:
    - name: Build Feature Branch and Raise PR
      run: |
        # Setup git details
        export GITHUB_USER=zapbot
        git config --global user.email "12745184+zapbot@users.noreply.github.com"
        git config --global user.name $GITHUB_USER
        # Clone repos
        git clone https://github.com/AliasIO/wappalyzer.git --depth 1
        git clone -o upstream https://github.com/zaproxy/zap-extensions.git
        cd zap-extensions
        git remote add origin https://github.com/$GITHUB_USER/zap-extensions.git
        cd ../wappalyzer
        # Setup env vars for later
        SRC_BASE="AliasIO/Wappalyzer@"$(git log -1 --format=format:%h)
        BRANCH_STAMP="$(date +"%Y%m%d%H%M%S")"
        SHORT_DATE="$(date +"%Y-%m-%d")"
        export GITHUB_TOKEN=${{ secrets.ZAPBOT_TOKEN }}
        # Build the feature branch
        cd ../zap-extensions
        git checkout -b $BRANCH_STAMP
        cd ..
        rm -rf zap-extensions/addOns/wappalyzer/src/main/resources/org/zaproxy/zap/extension/wappalyzer/resources/icons
        chmod -R 664 wappalyzer/src/drivers/webextension/images/icons/*.*
        rm -rf wappalyzer/src/drivers/webextension/images/icons/converted/
        cp -R wappalyzer/src/drivers/webextension/images/icons/ zap-extensions/addOns/wappalyzer/src/main/resources/org/zaproxy/zap/extension/wappalyzer/resources/icons
        cp -f wappalyzer/src/technologies.json zap-extensions/addOns/wappalyzer/src/main/resources/org/zaproxy/zap/extension/wappalyzer/resources/apps.json
        cd zap-extensions
        ## Update the index to be sure git is aware of changes
        git update-index -q --refresh
        ## If there are changes: comment, commit, PR
        if ! git diff-index --quiet HEAD --; then
          ./gradlew :addOns:wappalyzer:updateChangelog --change="- Updated with upstream Wappalyzer icon and pattern changes."
          git remote set-url origin https://$GITHUB_USER:$GITHUB_TOKEN@github.com/$GITHUB_USER/zap-extensions.git
          git add .
          git commit -m "Wappalyzer Update $SHORT_DATE" -m "Updates based on $SRC_BASE" --signoff
          git push --set-upstream origin $BRANCH_STAMP
          # Open the PR
          hub pull-request --no-edit
        fi
